### ISSUE TITLE
Error: iterator function called with non-iterator argument

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#26]
When I load the project in R I see the following error being printed in the console:

Error: iterator function called with non-iterator argument

Anyone else see this? Any idea where it's coming from?

**Comment by jacob-gg** [comment]
Interesting: I'm not seeing the error when I open the .Rproj---maybe we can check things out Wednesday? I've also been running into an issue where the Python `read_xml()` call in the Importing Data chapter doesn't work, so I usually have to set `eval = F` for that chunk before rendering (and then change it back before pushing). Has anyone else run into this?

**Comment by jeffkeller-einc** [comment]
> `Error: iterator function called with non-iterator argument`

This is a bug in the Python data viewer in RStudio: https://github.com/rstudio/rstudio/issues/8355
