### ISSUE TITLE
Ch 7 - barplots feedback

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#27]
I had opened the barplots section with "Visualizing the distribution of _categorical data_." So I was hoping we would use categorical data here. I guess we can use means, but that's a lot of ink for 3 data points. [This article](https://simplystatistics.org/2019/02/21/dynamite-plots-must-die/) makes similar points about dynamite plots, which are basically bar plots of means with error bars.

Maybe we could do something like this instead?

```
species <- xtabs(~ species, data = penguins) |> as.data.frame()
barplot(Freq ~ species, data = species,
        col = c('lightblue', 'cornflowerblue', 'darkslateblue'),
        main = 'Species Sample Size', 
        xlab = 'Species', 
        ylab = 'Count')
```

Thoughts? Objections?

**Comment by jacob-gg** [comment]
Ten-four! Apologies: I somehow missed the categorical note the first time around. I'll update that! Thanks for the heads up.

**Comment by jacob-gg** [comment]
Updated: bd18c6fb8978bddebcc181210ab450e7083a32ac.
