### ISSUE TITLE
Ch 7 - histograms, python

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#32]
Take a first crack at making a python version of the corresponding R plot.

**Comment by clayford** [comment]
Why is there array output in the code chunk? I know you didn't type that in. I'll look into it, but wondered if you knew? 

[https://uvastatlab.github.io/Python_and_R/basic-plotting-and-visualization.html#histograms](https://uvastatlab.github.io/Python_and_R/basic-plotting-and-visualization.html#histograms)

**Comment by slomuscio** [comment]
Good catch,I didn't notice that! I just re-looked into the documentation and the matplotlib hist() function returns a tuple with some info about the histogram it produces. I'll see if there's a simple way to stop it from printing that.

**Comment by clayford** [comment]
Apparently you just need to add a semicolon at the end of the hist() function. See [https://stackoverflow.com/questions/30263135/frequency-histogram-with-matplotlib-how-to-get-rid-of-the-array-display](https://stackoverflow.com/questions/30263135/frequency-histogram-with-matplotlib-how-to-get-rid-of-the-array-display)

I did that and it seemed to fix it.
