### ISSUE TITLE
Ch 7 - stripcharts, R

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#34]
I think this should use the same data as the boxplot example, but use geom_jitter(width = 0.1, height = 0) instead of geom_boxplot(). There's also a stripchart() function in base R, but not sure we need to demonstrate it.

**Comment by jacob-gg** [comment]
Added 2022-01-11; commits 4465a6c and 2af5421.

**Comment by clayford** [comment]
Since the chapter opens with "we discuss how to generate plots using base R and using ggplot2" I would go ahead and demonstrate the base R stripchart function for completeness. Plus I make quick use of it in Ch 8 to visualize the distribution of values between groups. Thanks!

**Comment by jacob-gg** [comment]
Added! 0a42025
