### ISSUE TITLE
Ch 1, section 1.4 - Python packages

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#37]
Explain what Python packages are and how to install.

**Comment by oadenekan123** [comment]
to download packages in Python, I usually use an Anaconda command window. should i write about downloading packages via Anaconda ? i think it could be useful to talk about some sort of python package management system, but perhaps it makes things more complex

**Comment by oadenekan123** [comment]
images folder

2 options for image import
knitr (chapter 3 merge)
Help --> markdown quick reference
