### ISSUE TITLE
Ch 7 - section 7.6, facet plots - coplot() review

### ISSUE THREAD

**Issue by clayford** [uvastatlab/Python_and_R#42]
Jacob, I added coplot() as a base R example of facet plots. Can you review and edit as needed? Feel free to do a wholesale re-write!! I'm also wondering if it should come _after_ the ggplot example, and then just show how it can condition on a numeric variable. Since we mentioned base R examples (which I like!) I thought we should include this function. But I'm curious about your thoughts on how we should work it in.

**Comment by jacob-gg** [comment]
Great addition! All seems clear to me. I only made tiny changes (e.g., adding `()` after a function name, etc.): e784d30

To stay consistent with the other plot examples earlier in the chapter, I think putting base R first make sense. The `coplot()` section isn't particularly long, so I don't think it pushes the ggplot2 material so low that it becomes hard to find/unlikely to be found. Super useful to see how `coplot()` can facet based on numeric variables too.
