### ISSUE TITLE
Ch 6 - look at 6.2

### ISSUE THREAD

**Issue by oadenekan123** [uvastatlab/Python_and_R#48]

**Comment by oadenekan123** [comment]
i think this section look quite good. perhaps comments between the cross tab piece of code and the group by piece of code could help with readability, just to separate the sections. i dont think it is necessary tho

**Comment by slomuscio** [comment]
I think this section is really well written! I was able to follow everything really easily. The explanations and examples were all very clear & demonstrated the functions well
